FROM rust:latest

RUN apt-get update -yqq && apt-get install -yqq cmake g++

ADD ./ /rust_marcenaria
WORKDIR /rust_marcenaria

RUN cargo clean
RUN rustup self update
RUN rustup update
RUN RUSTFLAGS="-C target-cpu=native" cargo build --release

EXPOSE 8080

CMD ./target/release/rust_marcenaria
