FROM maven:3.9.6-eclipse-temurin-21 as maven
WORKDIR /vertx
COPY src src
COPY pom.xml pom.xml
RUN mvn clean package -q

EXPOSE 8888

CMD ["java", "--enable-preview", "-Xms2G", "-Xmx2G", "-server", "-XX:+UseNUMA", "-XX:+UseParallelGC", "-Dvertx.disableMetrics=true", "-Dvertx.disableH2c=true", "-Dvertx.disableWebsockets=true", "-Dvertx.flashPolicyHandler=false", "-Dvertx.threadChecks=false", "-Dvertx.disableContextTimings=true", "-Dvertx.disableTCCL=true", "-Dvertx.disableHttpHeadersValidation=true", "-Dio.netty.buffer.checkBounds=false", "-Dio.netty.buffer.checkAccessible=false", "-jar", "target/java-vertx-1.0-SNAPSHOT-fat.jar"]