FROM golang:latest AS build

WORKDIR /go/src/marcenaria

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o app .

FROM alpine:latest as release

WORKDIR /app

COPY --from=build /go/src/marcenaria/app .

RUN apk -U upgrade \
    && apk add --no-cache dumb-init ca-certificates \
    && chmod +x /app/app

EXPOSE 8080

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
